version: '3'

networks:
    nginx-php81-postgres-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php81-service
            - postgres-service
        networks:
            - nginx-php81-postgres-node

    # php
    php81-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php81-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php81-postgres-node

    # postgres
    postgres-service:
        image: postgres:15-alpine
        container_name: postgres-container
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: bagu
        networks:
            - nginx-php81-postgres-node

    # node
    node-service:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: angular-container
        volumes:
        - ./frontend:/var/www/project
        ports:
        - "4200:4200"  # Map port 4200 on the host to port 4200 in the container
        networks:
        - nginx-php81-postgres-node
